### PR TITLE
2.0

### LINKED ISSUE #9: create method
Just to delegate all the work with buffers to the lib.

``` js
util.create(); //create minimal valid instance
util.create([ch1array, ch2array, ...]); //for the case of audio-worker in issue #8
util.create(2,2,44100); //wrapper over new AudioBuffer(ch, len, rate) or ctx.createBuffer() or whatever
util.create(otherBuffer); //clone
util.create(arrayBuffer); //from specific data
...
```

Possible names:
-  `util.new()`
-  `util.create()`
-  `util.from()`

@jaz303 which one is better? `.from` is conventional, like `Array.from`, but `.create` is unambiguous.

### PR DESCRIPTION
**Pull request by dy**
- Added `create` method
- Added `target` optional argument
- Enhanced `shallow` performance
- Enhanced recognition of `start` and `end` arguments
- Added `copy` method

@jaz303 please review.

Closes #9 and #2.

### CODE REVIEW

**Comment by dy** [comment]
@jaz303 any comments?

**Comment by jaz303** [comment]
Travelling today will review tomorrow

**Comment by dy** [comment]
ok

**Comment by dy** [comment]
@jaz303 what’s up?
[Audio-through](https://github.com/audio-lab/audio-through) depends on it already - very useful!

**Comment by dy** [comment]
@jaz303 it becomes a kind of urgent. I’m going to merge it tomorrow.

**Pull request merged**
