### PR TITLE
Set of major changes

### PR DESCRIPTION
**Pull request by dy**
Hello, Jason!

This is a PR-question.

I’ve taken the significant liberty of adding my interpretation to your library by significant extending the API and reworking the infrastructure (a bit).

Things which have done:
- Each util method is covered with tests.
- `clone` method now works.
- Removed `/build`, as it is not a good practice to store builds in repo, it is better to be avoided, but as a last resort it should be done with [`prepublish` script](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/).
- Methods also work with node implementation of [audio-buffer](https://github.com/audio-lab/buffer) (in browser it is just a constructor of WebAudioAPI AudioBuffers).
- Lots of new (I believe useful) methods, and list is not complete...

So the question is — whether you’re ready to accept such drastic changes and step into the future of _audio-buffer-utils_ :satisfied: or I should better register separate package in the npm under the name `audio-buffer-util`? I’d better keep to the current one, as the current API didn’t change at all and isn’t going to change, also I don’t like really lots of duplicates in the npm, but decision is up to you :)

Thank you for checking out and Im looking forward!

### CODE REVIEW

**Comment by jaz303** [comment]
Hey, this is awesome - definitely up for including it. Will review properly later.

**Comment by dy** [comment]
Awesome! There is some other bunch of function is coming, for the release 1.0.0

**Comment by jaz303** [comment]
cool, what are you planning?

**Comment by dy** [comment]
Most of the shallow functions (with xxx body) in index.js. Except for fft/ifft probably

**Pull request merged**
